name: Ubuntu 22.04 Jazzy Build

on:
  pull_request:
  push:
    branches:
      - iron
  schedule:
    # At 2:10 each day
    - cron:  '10 02 * * 0'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  Build:
    timeout-minutes: 10
    runs-on: self-hosted
    container:
      image: ${{ vars.LOCAL_DOCKER_REGISTRY_IP }}:5000/roxy_jazzy:base

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run Tests
      timeout-minutes: 10
      uses: ros-tooling/action-ros-ci@0.3.16
      with:
        target-ros2-distro: jazzy
        skip-rosdep-install: true
        colcon-defaults: |
          {
            "build": {
                "merge-install": true,
                "cmake-args": [
                    "-D_FORTIFY_SOURCE=3",
                    "-D_GLIBCXX_ASSERTIONS=1",
                    "-DCMAKE_C_FLAGS=-march=native -fopenmp",
                    "-DCMAKE_CXX_FLAGS=-march=native -fopenmp"
                ]
            },
            "test": {
                "merge-install": true
            }
          }
